theme: jekyll-theme-cayman
title: "Spiking neural networks as universal function approximators: Learning algorithms and applications"
description: An online workshop on training spiking neural networks to perform complex information processing.
show_downloads: false
github:
  is_project_page: false
